# Generated by Django 4.0.4 on 2022-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_reader_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='card_number_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старый читательский билет'),
        ),
    ]
