# Generated by Django 4.0.4 on 2022-05-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_reader_card_number_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('file', models.FileField(upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Название книги')),
            ],
        ),
    ]
