# Generated by Django 4.0.4 on 2022-05-24 15:47

from django.db import migrations, models
import library_app.models
import library_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_bookcover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcover',
            name='filename',
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='file',
            field=models.FileField(upload_to=library_app.models.get_upload_path, validators=[library_app.validators.validate_file_size, library_app.validators.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер файла'),
        ),
    ]
