# Generated by Django 4.0.4 on 2022-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_remove_bookcover_filename_alter_bookcover_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Роман', 'Роман'), ('Повесть', 'Повесть'), ('Рассказ', 'Рассказ'), ('Поэма', 'Поэма'), ('Сказка', 'Сказка')], default='-', max_length=300, null=True, verbose_name='Жанр'),
        ),
    ]
