# Generated by Django 4.0.4 on 2022-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
