# Generated by Django 4.0.4 on 2022-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_review_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='review_book',
        ),
        migrations.AddField(
            model_name='book',
            name='book_review',
            field=models.ManyToManyField(to='library_app.review', verbose_name='Отзывы'),
        ),
    ]
