# Generated by Django 4.0.4 on 2022-06-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_rename_book_review_review_book_book_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
